#!/bin/sh


lnumber=0
cat temp/egsprice/list.txt | while read line
do
lnumber=$(($lnumber + 1))
name=$line
search=$(echo $name | tr ' ' '%20')
url="https://store.epicgames.com/en-US/browse?q="$search"&sortBy=relevancy"

error=$(curl -A 'random' -s $url | grep -Eo "No results found</span>" | head -n 1)

case $error in
	"")
		price=$(curl -A 'random' -s $url | grep -Eo "€[0-9]{1,2}.[0-9]{2}" | head -n 1 | grep -Eo "[0-9]{1,2}.[0-9]{2}")
		firsturl="https://store.epicgames.com"$(curl -A 'random' -s $url | grep -Eo "/en-US/p/[a-zA-Z?%-][^\"]{1,}" |head -n 1)
		echo -e  $price"€ \t"$name "("$firsturl")" >> temp/egsprice/listwithprice.txt
		echo -e "("$lnumber"/157) "$price"€ \t"$name "("$firsturl")"
	;;
	*)
		echo $name": no results" >> temp/egsprice/listwithprice.txt
		echo "("$lnumber"/157)" $name": no results"
	;;
esac
done
